# Packages used in Muylaert et al. sarbecovirus hosts distribution
# Make sure you are in distribution_models project

P <- c("here","stringr","spocc", "data.table", "dplyr", "ggmap", "ggplot2", "ggsn", "maps", "mapdata" )

for(p in P){
  if(!require(p,character.only = TRUE)) install.packages(p)
  library(p,character.only = TRUE)
}

lapply(P, library, character.only = TRUE)

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

#devtools::install_github("thomasp85/scico")
require(DataExplorer)
require(xlsx)
library(raster)
library(rasterVis)
library(tidyverse)
library(dplyr)
library(skimr)
require(viridis)
library(ggpubr)
library(gghighlight)
library(ggplot2)
library(ggmap)
library(ggbump)
require(ggspatial)
require(taxize)
require(stringr)
library(randomcoloR)
require(data.table)
require(spatialEco)
library(CoordinateCleaner)
library(ecospat)
library(lubridate)
require(tmap)
library(lattice)
library(maps)
library(sp)
require(sf)
library(ncdf4)
library(leaflet)
library(randomcolorR)
require(platexpress)
library(leafem)
library(rnaturalearth)
library(rnaturalearthdata)
library(htmlwidgets)
library(htmltools)
require(stringi)
require(manu)
require(Rcpp)
require(platexpress)
library(RColorBrewer)
library(magrittr)
library(igraph)
library(ggraph)
library(graphlayouts)
library(oaqc)
require(spData)
require(reshape2)
library(leaflet.opacity)
library(lattice)
library(dplyr)
library(hrbrthemes)
require(bipartite)
require(rredlist)
require(corrplot)
require(rstatix)
library(MuMIn)
library(vroom)
library(wesanderson)
#############################################################################################################